(() => {
  const BUILD = '2026.08.23.5';
  const EXPECTED_CACHE = 'italy-2026-app-v30';
  function ensureStyles(){if(document.getElementById('app-status-styles'))return;const style=document.createElement('style');style.id='app-status-styles';style.textContent=`.app-status-card{margin-top:18px;padding:14px 16px;border:1px solid var(--line);border-radius:16px;background:var(--card)}.app-status-row{display:flex;align-items:center;justify-content:space-between;gap:14px}.app-status-row+.app-status-row{margin-top:9px;padding-top:9px;border-top:1px solid var(--line)}.app-status-label{font-size:12px;color:var(--muted);font-weight:750}.app-status-value{font-size:12px;font-weight:850;text-align:right}.app-status-value.ready{color:#17603f}.app-status-value.waiting{color:var(--muted)}`;document.head.appendChild(style)}
  function removeLegacyOfflineCard(more){more.querySelectorAll('.info-card').forEach(card=>{const heading=card.querySelector('strong')?.textContent?.trim().toLowerCase();if(heading==='offline-ready'||heading==='offline ready')card.remove()});more.querySelector('.app-update-card')?.remove()}
  async function offlineState(){if(!('serviceWorker'in navigator)||!('caches'in window))return{label:'Unavailable',ready:false};try{const registration=await navigator.serviceWorker.ready;const keys=await caches.keys();const ready=Boolean(registration.active&&keys.includes(EXPECTED_CACHE));return ready?{label:'Offline ready ✓',ready:true}:{label:'Preparing offline…',ready:false}}catch{return{label:'Offline status unavailable',ready:false}}}
  async function renderStatus(){ensureStyles();const more=document.getElementById('more');if(!more||more.classList.contains('hidden'))return;removeLegacyOfflineCard(more);let card=more.querySelector('.app-status-card');if(!card){card=document.createElement('section');card.className='app-status-card';more.appendChild(card)}card.innerHTML=`<div class="app-status-row"><span class="app-status-label">Offline</span><span class="app-status-value waiting">Checking…</span></div><div class="app-status-row"><span class="app-status-label">App version</span><span class="app-status-value">${BUILD}</span></div>`;const state=await offlineState();if(!card.isConnected)return;const value=card.querySelector('.app-status-value');value.textContent=state.label;value.classList.toggle('ready',state.ready);value.classList.toggle('waiting',!state.ready)}
  async function checkForUpdates(){if(!('serviceWorker'in navigator))return;try{const registration=await navigator.serviceWorker.getRegistration();if(registration)await registration.update()}catch(error){console.error('Unable to check for app update',error)}}
  document.addEventListener('click',event=>{if(event.target.closest('[data-target="more"]'))setTimeout(renderStatus,0)});
  window.addEventListener('focus',checkForUpdates);
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkForUpdates()});
  window.addEventListener('load',()=>{checkForUpdates();setTimeout(renderStatus,250)});
})();
