const trip=window.TRIP_DATA,hotels=window.HOTELS,remaining=window.REMAINING;const P='italy2026-v4-';
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}
function id(d,e,i){return(d.date+'-'+i+'-'+e.title).replace(/[^a-z0-9]+/gi,'-').toLowerCase()}
function done(k){try{return localStorage.getItem(P+'done-'+k)==='1'}catch{return false}}
function setDone(k,v){try{localStorage.setItem(P+'done-'+k,v?'1':'0')}catch{}}
function card(d,open=false){return `<article class="card ${open?'open':''}" data-city="${d.city}"><button class="dayhead"><div><div class="date">${fmtDate(d.date)} — ${d.title}</div><div class="city">${d.city}</div></div><div class="chev">⌄</div></button><div class="body">${d.events.map((e,i)=>{const k=id(d,e,i),x=done(k);return `<div class="event ${x?'done':''}" data-event="${k}"><input class="check" type="checkbox" ${x?'checked':''}><div class="time">${e.time}</div><div><div class="title">${e.title}</div><div class="note">${e.note}</div>${e.status?`<span class="badge ${e.status==='To book'?'warn':''}">${e.status}</span>`:''}${e.map?`<br><a class="map" href="${e.map}" target="_blank">Open in Maps</a>`:''}</div></div>`}).join('')}</div></article>`}
function bind(){document.querySelectorAll('.dayhead').forEach(b=>b.onclick=()=>b.closest('.card').classList.toggle('open'));document.querySelectorAll('.check').forEach(c=>c.onchange=()=>{const r=c.closest('.event');setDone(r.dataset.event,c.checked);r.classList.toggle('done',c.checked);progress()})}
function progress(){const c=[...document.querySelectorAll('#today .check')],n=c.filter(x=>x.checked).length;if(document.querySelector('#today .bar'))document.querySelector('#today .bar').style.width=(c.length?100*n/c.length:0)+'%';if(document.querySelector('#today .progressText'))document.querySelector('#today .progressText').textContent=`${n} of ${c.length} completed`}
function nextFor(d){if(!d)return null;return d.events.map((e,i)=>({e,i})).find(x=>!done(id(d,x.e,x.i)))||null}
const iso=new Date().toISOString().slice(0,10),todayDay=trip.find(d=>d.date===iso),next=nextFor(todayDay);document.getElementById('today').innerHTML=`<div class="section"><h2>Today</h2>${todayDay?(next?`<div class="next"><div class="next-label">Next activity</div><div class="next-title">${next.e.title}</div><b>${next.e.time}</b><div class="note">${next.e.note}</div></div>`:`<div class="callout">All activities completed.</div>`)+`<div class="info"><b>Today's progress</b><div class="progress"><div class="bar"></div></div><div class="small progressText"></div></div>${card(todayDay,true)}`:`<div class="callout">During the trip, this screen will show the current day and next activity.</div>${card(trip[0],true)}`}</div>`;
const cities=['All','Flights','Venice','Florence','Rome','Naples','Capri'];document.getElementById('trip').innerHTML=`<div class="filters">${cities.map((c,i)=>`<button class="chip ${i?'':'active'}" data-city="${c}">${c}</button>`).join('')}</div><div id="cards">${trip.map((d,i)=>card(d,i===0)).join('')}</div>`;document.querySelectorAll('.chip').forEach(ch=>ch.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));ch.classList.add('active');document.querySelectorAll('#cards .card').forEach(c=>c.classList.toggle('hidden',ch.dataset.city!=='All'&&c.dataset.city!==ch.dataset.city))});
document.getElementById('bookings').innerHTML=`<div class="section"><h2>Hotels</h2><div class="grid">${hotels.map(h=>`<div class="info"><b>${h[0]} — ${h[1]}</b><div class="small">${h[3]}${h[2]?'<br>'+h[2]:''}</div></div>`).join('')}</div></div><div class="section"><h2>Remaining reservations</h2><div class="card" style="padding:0 14px">${remaining.map(r=>`<div class="statusrow"><span class="dot"></span><div><b>${r[0]}</b><div class="small">${r[1]}</div></div></div>`).join('')}</div></div>`;
const packs=['Passport','Wallet and credit cards','Phone charger','Portable battery','EU plug adapter','Medications','Walking shoes','Rain jacket','Sunglasses','Swimsuit for Capri','Printed backup reservations','Luggage tracker'];document.getElementById('packing').innerHTML=`<div class="section"><h2>Packing checklist</h2><div class="card" style="padding:0 14px">${packs.map((x,i)=>`<label class="pack-row"><input type="checkbox" data-pack="${i}" ${localStorage.getItem(P+'pack-'+i)==='1'?'checked':''}><span>${x}</span></label>`).join('')}</div></div>`;document.querySelectorAll('[data-pack]').forEach(x=>x.onchange=()=>localStorage.setItem(P+'pack-'+x.dataset.pack,x.checked?'1':'0'));
document.getElementById('notes').innerHTML=`<div class="section"><h2>More tools</h2><div class="grid"><button class="secondary" id="openBookings">Bookings overview</button><button class="secondary" id="openPacking">Packing checklist</button></div><h2>Trip notes</h2><textarea id="noteBox" placeholder="Reservation numbers, restaurant ideas, reminders..."></textarea><button class="save" id="saveNotes">Save notes</button><div class="small" id="savedMsg"></div></div>`;document.getElementById('noteBox').value=localStorage.getItem(P+'notes')||'';document.getElementById('saveNotes').onclick=()=>{localStorage.setItem(P+'notes',document.getElementById('noteBox').value);document.getElementById('savedMsg').textContent='Saved on this device.'};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(b.dataset.target).classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})});const start=new Date('2026-09-14'),end=new Date('2026-09-27T23:59:59'),now=new Date(),diff=Math.ceil((start-now)/86400000);document.getElementById('countdown').textContent=now<start?`${diff} days until departure`:now<=end?'Your Italy trip is underway':'Trip completed';bind();progress();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');